sportsevents/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

#create a blueprint
authbp = Blueprint('auth', __name__ )

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd)
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.name==user_name))
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

sportsevents/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Game Glory</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Optional Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-eN4R7RZQhFSZmOVN6f8XhWzqGd2ss2ur7SyvF+b2vNGG2+krh28S63LXlw7VhxU1" crossorigin="anonymous">
</head>
<body style="background-color: black;">
    <!-- Header -->
    <header class="bg-light border-bottom">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <!-- Your Travel App Name or Logo -->
                <a href="{{ url_for('main.index') }}" class="navbar-brand">Game Glory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- Register/Login/Logout and welcome -->
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <!-- Debug: Ensure the authentication check is working -->
                            <a class="nav-link" href="#" style="color: white;">Welcome {{ current_user.name }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('event.create') }}">Create Event</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.bookings') }}">Bookings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- Flash messages -->
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="container-fluid">
            <div class="row mt-3 mb-3">
                <div class="col-md-12">
                    {% for message in messages %}
                    <div class="alert alert-info">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endwith %}
    </header>

    {% block header %}{% endblock %}
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="bg-dark text-center text-white mt-4">
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-

sportsevents/templates/bookings.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='stylesheets/User_booking.css') }}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Game Glory</title>
    <style>
      body {
        background: url('https://png.pngtree.com/thumb_back/fh260/background/20240103/pngtree-assorted-grunge-patterns-on-vintage-tickets-image_13922333.png') no-repeat center center fixed;
        background-size: cover;
      }
      .event-image {
        height: 100px; /* Set the height to 100px */
        width: auto;   /* Maintain the aspect ratio */
        object-fit: contain; /* Ensure the entire image fits within the container */
      }
    </style>
  </head>
  <body>
    <header>
      {% block navbar %}{% endblock %}
    </header>
    
    <main>
        <div class="container-fluid">
            <div class="row">
                <div style="font-size: 100px; color: white; font-family: 'Brush Script MT', cursive;" class="container1">
                    <p>My Bookings</p>
                </div>
            </div>
            <div class="row">
                <table class="table align-middle mb-0 bg-white">
                    <thead class="bg-light">
                        <tr>
                            <th>Event</th>
                            <th>Event Name</th>
                            <th>Status</th>
                            <th>Time</th>
                            <th>Date</th>
                            <th>Booking ID</th>
                            <th>Number of Tickets</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for booking in bookings %}
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <img src="{{ booking.event.image }}" alt="{{ booking.event.name }}" class="img-fluid event-image" />
                                </div>
                            </td>
                            <td>
                                <p class="fw-normal mb-1">{{ booking.event.name }}</p>
                                <p class="text-muted mb-0">{{ booking.orderid }}</p>
                            </td>
                            <td>
                                <span style="background-color: grey; color: white;" class="badge badge-success rounded-pill d-inline">{{ booking.event.status }}</span>
                            </td>
                            <td class="booking-time" data-utc="{{ booking.booking_date.isoformat() }}">{{ booking.booking_date.strftime('%H:%M %p') }}</td>
                            <td class="booking-date" data-utc="{{ booking.booking_date.isoformat() }}">{{ booking.booking_date.strftime('%Y-%m-%d') }}</td>
                            <td>#{{ booking.orderid }}</td>
                            <td>{{ booking.number_of_tickets }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <footer style="background-image: url(http://m.gettywallpapers.com/wp-content/uploads/2023/12/Full-Black-4k-Wallpaper-For-Desktop.jpg);" class="text-center text-lg-start bg-body-tertiary text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
          <!-- Left -->
          <div style="color: white;" class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
          </div>
          <!-- Left -->
      
          <!-- Right -->
          <div>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
              <i class="fab fa-github"></i>
            </a>
          </div>
          <!-- Right -->
        </section>
        <!-- Section: Social media -->
      
        <!-- Section: Links  -->
        <section class="">
          <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
              <!-- Grid column -->
              <div style="color: white;" class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                  <i class="fas fa-gem me-3"></i>Game Glory
                </h6>
              </div>
              <!-- Grid column -->
      
              <!-- Grid column -->
              <div style="color: white;" class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                  Events
                </h6>
                <p>
                  <a href="index.html" class="text-reset">View Events</a>
                </p>
                <p>
                  <a href="index.html" class="text-reset">Sports</a>
                </p>
                <p>
                  <a href="bookings.html" class="text-reset">My Bookings</a>
                </p>
                <p>
                  <a href="create.html" class="text-reset">Create Events</a>
                </p>
              </div>
              <!-- Grid column -->
      
              <!-- Grid column -->
              <div style="color: white;" class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                  Useful links
                </h6>
                <p>
                  <a href="show.html" class="text-reset">Pricing</a>
                </p>
                <p>
                  <a href="#!" class="text-reset">Settings</a>
                </p>
                <p>
                  <a href="bookings.html" class="text-reset">Orders</a>
                </p>
                <p>
                  <a href="#!" class="text-reset">Help</a>
                </p>
              </div>
              <!-- Grid column -->
      
              <!-- Grid column -->
              <div style="color: white;" class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                <p><i class="fas fa-home me-3"></i> Brisbane, QLD , AUS</p>
                <p>
                  <i class="fas fa-envelope me-3"></i>
                  info@example.com
                </p>
                <p><i class="fas fa-phone me-3"></i> + 0123456789</p>
                <p><i class="fas fa-print me-3"></i> + 0123456789</p>
              </div>
              <!-- Grid column -->
            </div>
            <!-- Grid row -->
          </div>
        </section>
        <!-- Section: Links  -->
      
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
          © 2024 Copyright:
          <a class="text-reset fw-bold" href="https://mdbootstrap.com/">GameGlory.com</a>
        </div>
        <!-- Copyright -->
      </footer>

    <!-- Include Moment.js -->
    <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/min/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.34/moment-timezone-with-data.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const timeElements = document.querySelectorAll('.booking-time');
        const dateElements = document.querySelectorAll('.booking-date');

        timeElements.forEach(function(element) {
          const utcTime = element.getAttribute('data-utc');
          const localTime = moment.utc(utcTime).local().format('LT');
          element.textContent = localTime;
        });

        dateElements.forEach(function(element) {
          const utcDate = element.getAttribute('data-utc');
          const localDate = moment.utc(utcDate).local().format('LL');
          element.textContent = localDate;
        });
      });
    </script>
  </body>
</html>
{% endblock %}

sportsevents/templates/index.html
{% extends 'base.html' %}

{% block header %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<header>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <video class="d-block w-100" autoplay loop muted>
                    <source src="{{ url_for('static', filename='video/main_video.mp4') }}" type="video/mp4">
                </video>
                <div class="carousel-caption d-none d-md-block" style="font-family: 'Brush Script MT', cursive; padding-bottom: 340px;">
                    <h1 style="font-size: 100px;">Game Glory</h1>
                    <p style="font-size: 25px;">Experience the Feel of Victory.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{ url_for('static', filename='images/main_4.jpeg') }}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block" style="font-family: 'Brush Script MT', cursive; padding-bottom: 280px;">
                    <h2 style="font-size: 50px;">Discover the Thrill of Sports</h2>
                    <p style="font-size: 25px;">Unleash Your Inner Athlete with Us.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{ url_for('static', filename='images/main_5.jpeg') }}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block" style="font-family: 'Brush Script MT', cursive; padding-bottom: 340px;">
                    <h2 style="font-size: 50px;">Join the Champions</h2>
                    <p style="font-size: 25px;">Where Winning is a Tradition.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</header>
{% endblock %}

{% block content %}
<main>
    <div class="container-fluid">
        <div class="row text-white" style="font-family: Georgia, 'Times New Roman', Times, serif;">
            <div class="col-12 mb-4" style="font-size: 50px; font-family: 'Brush Script MT', cursive;">
                <p>All Events</p>
            </div>
            <!-- Event Cards -->
            {% for event in events %}
            <style>
                .card-custom {
                    border: none;
                    border-radius: 15px;
                    overflow: hidden;
                    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
                    transition: transform 0.3s, box-shadow 0.3s;
                    background: linear-gradient(145deg, #2a2a2a, #1a1a1a);
                    color: #e0e0e0;
                }
                .card-custom:hover {
                    transform: translateY(-10px);
                    box-shadow: 0 8px 40px rgba(0, 0, 0, 0.4);
                }
                .card-custom img {
                    border-top-left-radius: 15px;
                    border-top-right-radius: 15px;
                    height: 200px;
                    object-fit: cover;
                    filter: brightness(0.8);
                }
                .card-custom .card-body {
                    padding: 1.5rem;
                    position: relative;
                }
                .card-custom .badge {
                    position: absolute;
                    top: 1rem;
                    left: 1rem;
                    padding: 0.5rem 1rem;
                    font-size: 0.9rem;
                    background: grey;
                    color: #fff;
                    text-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
                }
                .card-custom .card-title {
                    font-size: 1.5rem;
                    font-weight: 700;
                    text-transform: uppercase;
                    letter-spacing: 1px;
                    margin-top: 2rem; /* Added margin top to separate from badge */
                }
                .card-custom .card-text {
                    color: #b0b0b0;
                    font-size: 1rem;
                    margin-bottom: 1rem; /* Adjusted margin bottom */
                    max-height: 100px; /* Added max height for overflow */
                    overflow: hidden;
                }
                .card-custom .btn {
                    border-radius: 30px;
                    padding: 0.5rem 1.5rem;
                    font-size: 1rem;
                    background: linear-gradient(145deg, #007bff, #0056b3);
                    border: none;
                    transition: background 0.3s, transform 0.3s;
                    margin-top: 1rem; /* Added margin top to separate from text */
                }
                .card-custom .btn:hover {
                    background: linear-gradient(145deg, #0056b3, #007bff);
                    transform: scale(1.05);
                }
            </style>
            
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 mb-4">
                <div class="card card-custom">
                    <img src="{{ event.image }}" class="card-img-top" alt="{{ event.name }}">
                    <div class="card-body text-black">
                        <span class="badge rounded-pill">{{ event.status }}</span>
                        <h5 class="card-title">{{ event.name }}</h5>
                        <p class="card-text">{{ event.description }}</p>
                        <a href="{{ url_for('event.show', id=event.id) }}" class="btn btn-primary">Event Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
<footer style="background-image: url(http://m.gettywallpapers.com/wp-content/uploads/2023/12/Full-Black-4k-Wallpaper-For-Desktop.jpg);" class="text-center text-lg-start bg-body-tertiary text-muted"><!-- Footer -->
        
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div style="color: white;" class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div style="color: white;" class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Game Glory
            </h6>
            
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div style="color: white;" class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Events
            </h6>
            <p>
              <a href="index.html" class="text-reset">View Events</a>
            </p>
            <p>
              <a href="index.html" class="text-reset">Sports</a>
            </p>
            <p>
              <a href="bookings.html" class="text-reset">My Bookings</a>
            </p>
            <p>
              <a href="create.html" class="text-reset">Create Events</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div style="color: white;" class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="show.html" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="bookings.html" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div style="color: white;" class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> Brisbane, QLD , AUS</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 0123456789</p>
            <p><i class="fas fa-print me-3"></i> + 0123456789</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2024 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">GameGlory.com</a>
    </div>
    <!-- Copyright -->
  
  <!-- Footer --></footer>

{% endblock %}

sportsevents/templates/user.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<div class="container mt-5">
  <div class="page-header text-center mb-4">
    <h4 class="text-danger">{{ heading }}</h4>
  </div>
  <div class="row">
    <div class="col-md-6 d-flex align-items-center justify-content-center">
      <img src="{{ url_for('static', filename='images/login.jpeg') }}" class="img-fluid rounded" alt="Descriptive Alt Text">
    </div>
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          {{ render_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background-color: #f8f9fa; /* Light grey background */
  }

  .page-header {
    margin-bottom: 20px;
  }

  .page-header h4 {
    padding-left: 100px;
    font-family: 'Arial Black', Gadget, sans-serif;
    color: #ff0000; /* Red color */
  }

  .card {
    border: none; /* Remove default card border */
    border-radius: 10px; /* Rounded corners */
    background-color: #ffffff; /* White background */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow */
  }

  .card-body {
    padding: 20px;
  }

  .form-control {
    border-radius: 5px; /* Rounded corners for form inputs */
    border: 1px solid #ced4da; /* Light grey border */
  }

  .btn-primary {
    background-color: #000000; /* Black color */
    border-color: #000000; /* Black border */
    border-radius: 5px; /* Rounded corners for buttons */
  }

  .btn-primary:hover {
    background-color: #444444; /* Dark grey on hover */
    border-color: #444444; /* Dark grey border on hover */
  }

  .img-fluid {
    max-width: 100%; 
    height: auto;
    border-radius: 10px;
  }
</style>
{% endblock %}